name: aws-ecs
description: deploy aws ecs
inputs:
  key:
    description: 'AWS Access Key ID'
    required: true
  secret:
    description: 'AWS Secret Access Key'
    required: true
  region:
    description: 'Region name (default: us-east-1)'
    required: false
    default: us-east-1
  environment-yaml:
    description: 'jinja2 template input json data file.'
    required: true
  template-group:
    description: 'For multiple repositories ecs cluster deployment. When delete unused service with multiple repositories deployment, service and scheduled task settings exists for each repository. Then, only matches between template-group and ecs task-definition`s environment TEMPLATE_GROUP value are targeted.'
    required: false
runs:
  using: 'docker'
  image: 'docker://wacul/aws-ecs:latest'
  args:
    - service
    - --key ${{ inputs.key }}
    - --secret ${{ inputs.secret }}
    - --region ${{ inputs.region }}
    - --environemnt-yaml ${{ inputs.environment-yaml }}
    - --template-group ${{ inputs.template-group }}
    - --dry-run
